# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

lady = Category.create(name:"レディース")
man = Category.create(name:"メンズ")
baby = Category.create(name:"ベビー・キッズ")
housing = Category.create(name:"インテリア・住まい・小物")
book = Category.create(name:"本・音楽・ゲーム")
toy = Category.create(name:"おもちゃ・ホビー・グッズ")
beauty = Category.create(name:"コスメ・香水・美容")
camera = Category.create(name:"家電・スマホ・カメラ")
sports = Category.create(name:"スポーツ・レジャー")
handmade = Category.create(name:"ハンドメイド")
ticket = Category.create(name:"チケット")
car = Category.create(name:"自転車・オートバイ")
other = Category.create(name:"その他")

lady_1 = lady.children.create(name: "トップス")
lady_2 = lady.children.create(name: "ジャケット/アウター")
lady_3 = lady.children.create(name: "パンツ")
lady_4 = lady.children.create(name: "スカート")
lady_5 = lady.children.create(name: "ワンピース")
lady_6 = lady.children.create(name: "靴")
lady_7 = lady.children.create(name: "ルームウェア/パジャマ")
lady_8 = lady.children.create(name: "レッグウェア")
lady_9 = lady.children.create(name: "帽子")
lady_10 = lady.children.create(name: "バッグ")
lady_11 = lady.children.create(name: "アクセサリー")
lady_12 = lady.children.create(name: "ヘアアクセサリー")
lady_13 = lady.children.create(name: "小物")
lady_14 = lady.children.create(name: "時計")
lady_15 = lady.children.create(name: "ウィッグ/エクステ")
lady_16 = lady.children.create(name: "浴衣/水")
lady_17 = lady.children.create(name: "スーツ/フォーマル/ドレス")
lady_18 = lady.children.create(name: "マタニティ")
lady_19 = lady.children.create(name: "その他")

lady_1.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "キャミソール"}, {name: "タンクトップ"}, {name: "ホルターネック"}, {name: "ニット/セーター"}, {name: "チュニック"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "ベアトップ/チューブトップ"}, {name: "ジャージ"}, {name: "その他"}])
lady_2.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "レザージャケット"}, {name: "ダウンジャケット"}, {name: "ライダースジャケット"}, {name: "ミリタリージャケット"}, {name: "ダウンベスト"}, {name: "ジャンパー/ブルゾン"}, {name: "ポンチョ"}, {name: "ロングコート"}, {name: "トレンチコート"}, {name: "ダッフルコート"}, {name: "ピーコート"}, {name: "チェスターコート"}, {name: "モッズコート"}, {name: "スタジャン"}, {name: "毛皮/ファーコート"}, {name: "スプリングコート"}, {name: "スカジャン"}, {name: "その他"}])
lady_3.children.create([{name: "デニム/ジーンズ"}, {name: "ショートパンツ"}, {name: "カジュアルパンツ"}, {name: "ハーフパンツ"}, {name: "チノパン"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "クロップドパンツ"}, {name: "サロペット/オーバーオール"}, {name: "オールインワン"}, {name: "サルエルパンツ"}, {name: "ガウチョパンツ"}, {name: "その他"}])
lady_4.children.create([{name: "ミニスカート"}, {name: "ひざ丈スカート"}, {name: "ロングスカート"}, {name: "キュロット"}, {name: "その他"}])
lady_5.children.create([{name: "ミニワンピース"}, {name: "ひざ丈ワンピース"}, {name: "ロングワンピース"}, {name: "その他"}])
lady_6.children.create([{name: "ハイヒール/パンプス"}, {name: "ブーツ"}, {name: "サンダル"}, {name: "スニーカー"}, {name: "ミュール"}, {name: "モカシン"}, {name: "ローファー/革靴"}, {name: "フラットシューズ/バレエシューズ"}, {name: "長靴/レインシューズ"}, {name: "その他"}])
lady_7.children.create([{name: "パジャマ"}, {name: "ルームウェア"}, {name: "その他"}])
lady_8.children.create([{name: "ソックス"}, {name: "スパッツ/レギンス"}, {name: "ストッキング/タイツ"}, {name: "レッグウォーマー"}, {name: "その他"}])
lady_9.children.create([{name: "ニットキャップ/ビーニー"}, {name: "ハット"}, {name: "ハンチング/ベレー帽"}, {name: "キャップ"}, {name: "キャスケット"}, {name: "麦わら帽子"}, {name: "その他"}])
lady_10.children.create([{name: "ハンドバッグ"}, {name: "トートバッグ"}, {name: "エコバッグ"}, {name: "リュック/バックパック"}, {name: "ボストンバッグ"}, {name: "スポーツバッグ"}, {name: "ショルダーバッグ"}, {name: "クラッチバッグ"}, {name: "ポーチ/バニティ"}, {name: "ボディバッグ/ウェストバッグ"}, {name: "マザーズバッグ"}, {name: "メッセンジャーバッグ"}, {name: "ビジネスバッグ"}, {name: "旅行用バッグ/キャリーバッグ"}, {name: "ショップ袋"}, {name: "和装用バッグ"}, {name: "かごバッグ"}, {name: "その他"}])
lady_11.children.create([{name: "ネックレス"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "イヤリング"}, {name: "アンクレット"}, {name: "ブローチ/コサージュ"}, {name: "チャーム"}, {name: "その他"}])
lady_12.children.create([{name: "ヘアゴム/シュシュ"}, {name: "ヘアバンド/カチューシャ"}, {name: "ヘアピン"}, {name: "その他"}])
lady_13.children.create([{name: "長財布"}, {name: "折り財布"}, {name: "コインケース/小銭入れ"}, {name: "名刺入れ/定期入れ"}, {name: "キーケース"}, {name: "キーホルダー"}, {name: "手袋/アームカバー"}, {name: "ハンカチ"}, {name: "ベルト"}, {name: "マフラー/ショール"}, {name: "ストール/スヌード"}, {name: "バンダナ/スカーフ"}, {name: "ネックウォーマー"}, {name: "サスペンダー"}, {name: "サングラス/メガネ"}, {name: "モバイルケース/カバー"}, {name: "手帳"}, {name: "イヤマフラー"}, {name: "傘"}, {name: "レインコート/ポンチョ"}, {name: "ミラー"}, {name: "タバコグッズ"}, {name: "その他"}])
lady_14.children.create([{name: "腕時計(アナログ)"}, {name: "腕時計(デジタル)"}, {name: "ラバーベルト"}, {name: "レザーベルト"}, {name: "金属ベルト"},{name: "その他"}])
lady_15.children.create([{name: "前髪ウィッグ"}, {name: "ロングストレート"}, {name: "ロングカール"}, {name: "ショートストレート"}, {name: "ショートカール"}, {name: "その他"}])
lady_16.children.create([{name: "浴衣"}, {name: "着物"}, {name: "振袖"}, {name: "長襦袢/半襦袢"}, {name: "水着セパレート"}, {name: "水着ワンピース"}, {name: "水着スポーツ用"}, {name: "その他"}])
lady_17.children.create([{name: "スカートスーツ上下"}, {name: "パンツスーツ上下"}, {name: "ドレス"}, {name: "パーティバッグ"}, {name: "シューズ"}, {name: "ウェディング"}, {name: "その他"}])
lady_18.children.create([{name: "トップス"}, {name: "アウター"}, {name: "インナー"}, {name: "ワンピース"}, {name: "パンツ/スパッツ"}, {name: "スカート"}, {name: "パジャマ"}, {name: "授乳服"}, {name: "その他"}])
lady_19.children.create([{name: "コスプレ"}, {name: "下着"}, {name: "その他"}])

man_1 = man.children.create(name: "トップス")
man_2 = man.children.create(name: "ジャケット/アウター")
man_3 = man.children.create(name: "パンツ")
man_4 = man.children.create(name: "靴")
man_5 = man.children.create(name: "バッグ")
man_6 = man.children.create(name: "スーツ")
man_7 = man.children.create(name: "帽子")
man_8 = man.children.create(name: "アクセサリー")
man_9 = man.children.create(name: "小物")
man_10 = man.children.create(name: "時計")
man_11 = man.children.create(name: "水着")
man_12 = man.children.create(name: "レッグウェア")
man_13 = man.children.create(name: "アンダーウェア")
man_14 = man.children.create(name: "その他")

man_1.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ"}, {name: "ポロシャツ"}, {name: "タンクトップ"}, {name: "ニット/セーター"}, {name: "パーカー"}, {name: "カーディガン"}, {name: "スウェット"}, {name: "ジャージ"}, {name: "ベスト"}, {name: "その他"}])
man_2.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "レザージャケット"}, {name: "ダウンジャケット"}, {name: "ライダースジャケット"}, {name: "ミリタリージャケット"}, {name: "ナイロンジャケット"}, {name: "フライトジャケット"}, {name: "ダッフルコート"}, {name: "ピーコート"}, {name: "ステンカラーコート"}, {name: "トレンチコート"}, {name: "モッズコート"}, {name: "チェスターコート"}, {name: "スタジャン"}, {name: "スカジャン"}, {name: "ブルゾン"}, {name: "マウンテンパーカー"}, {name: "ダウンベスト"}, {name: "ポンチョ"}, {name: "カバーオール"}, {name: "その他"}])
man_3.children.create([{name: "デニム/ジーンズ"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "スラックス"}, {name: "チノパン"}, {name: "ショートパンツ"}, {name: "ペインターパンツ"}, {name: "サルエルパンツ"}, {name: "オーバーオール"}, {name: "その他"}])
man_4.children.create([{name: "スニーカー"}, {name: "サンダル"}, {name: "ブーツ"}, {name: "モカシン"}, {name: "ドレス/ビジネス"}, {name: "長靴/レインシューズ"}, {name: "デッキシューズ"}, {name: "その他"}])
man_5.children.create([{name: "ショルダーバッグ"}, {name: "トートバッグ"}, {name: "ボストンバッグ"}, {name: "リュック/バックパック"}, {name: "ウエストポーチ"}, {name: "ボディバッグ"}, {name: "ドラムバッグ"}, {name: "ビジネスバッグ"}, {name: "トラベルバッグ"}, {name: "メッセンジャーバッグ"}, {name: "エコバッグ"}, {name: "その他"}])
man_6.children.create([{name: "スーツジャケット"}, {name: "スーツベスト"}, {name: "スラックス"}, {name: "セットアップ"}, {name: "その他"}])
man_7.children.create([{name: "キャップ"}, {name: "ハット"}, {name: "ニットキャップ/ビーニー"}, {name: "ハンチング/ベレー帽"}, {name: "キャスケット"}, {name: "サンバイザー"}, {name: "その他"}])
man_8.children.create([{name: "ネックレス"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "アンクレット"}, {name: "その他"}])
man_9.children.create([{name: "長財布"}, {name: "折り財布"}, {name: "マネークリップ"}, {name: "コインケース/小銭入れ"}, {name: "名刺入れ/定期入れ"}, {name: "キーケース"}, {name: "キーホルダー"}, {name: "ネクタイ"}, {name: "手袋"}, {name: "ハンカチ"}, {name: "ベルト"}, {name: "マフラー"}, {name: "ストール"}, {name: "バンダナ"}, {name: "ネックウォーマー"}, {name: "サスペンダー"}, {name: "ウォレットチェーン"}, {name: "サングラス/メガネ"}, {name: "モバイルケース/カバー"}, {name: "手帳"}, {name: "ストラップ"}, {name: "ネクタイピン"}, {name: "カフリンクス"}, {name: "イヤマフラー"}, {name: "傘"}, {name: "レインコート"}, {name: "ミラー"}, {name: "タバコグッズ"}, {name: "その他"}])
man_10.children.create([{name: "腕時計(アナログ)"}, {name: "腕時計(デジタル)"}, {name: "ラバーベルト"}, {name: "レザーベルト"}, {name: "金属ベルト"}, {name: "その他"}])
man_11.children.create([{name: "一般水着"}, {name: "スポーツ用"}, {name: "アクセサリー"}, {name: "その他"}])
man_12.children.create([{name: "ソックス"}, {name: "スパッツ/レギンス"}, {name: "レッグウォーマー"}, {name: "その他"}])
man_13.children.create([{name: "トランクス"}, {name: "ボクサーパンツ"}, {name: "その他"}])
man_14.children.create([{name: "その他"}])
             

baby_1 = baby.children.create(name: "ベビー服(女の子用)~95cm")
baby_2 = baby.children.create(name: "ベビー服(男の子用)~95cm")
baby_3 = baby.children.create(name: "ベビー服(男女兼用)~95cm")
baby_4 = baby.children.create(name: "キッズ服(女の子用)100cm~")
baby_5 = baby.children.create(name: "キッズ服(男の子用)100cm~")
baby_6 = baby.children.create(name: "キッズ服(男女兼用)100cm~")
baby_7 = baby.children.create(name: "キッズ靴")
baby_8 = baby.children.create(name: "子ども用ファッション小物")
baby_9 = baby.children.create(name: "おむつ/トイレ/バス")
baby_10 = baby.children.create(name: "外出/移動用品")
baby_11 = baby.children.create(name: "授乳/食事")
baby_12 = baby.children.create(name: "ベビー家具/寝具/室内用品")
baby_13 = baby.children.create(name: "おもちゃ")
baby_14 = baby.children.create(name: "行事/記念品")
baby_15 = baby.children.create(name: "その他")

baby_1.children.create([{name: "トップス"}, {name: "アウター"}, {name: "パンツ"}, {name: "おくるみ"}, {name: "その他"}])
baby_2.children.create([{name: "トップス"}, {name: "アウター"}, {name: "パンツ"}, {name: "おくるみ"}, {name: "その他"}])
baby_3.children.create([{name: "トップス"}, {name: "アウター"}, {name: "パンツ"}, {name: "おくるみ"}, {name: "その他"}])
baby_4.children.create([{name: "コート"}, {name: "ジャケット"}, {name: "トップス"}, {name: "パンツ"}, {name: "その他"}])
baby_5.children.create([{name: "コート"}, {name: "ジャケット"}, {name: "トップス"}, {name: "パンツ"}, {name: "その他"}])
baby_6.children.create([{name: "コート"}, {name: "ジャケット"}, {name: "トップス"}, {name: "パンツ"}, {name: "その他"}])
baby_7.children.create([{name: "靴下"}, {name: "帽子"}, {name: "エプロン"}, {name: "サスペンダー"}, {name: "その他"}])
baby_8.children.create([{name: "おむつ用品"}, {name: "おまる"}, {name: "トレーニングパンツ"}, {name: "ベビーパス"}, {name: "その他"}])
baby_9.children.create([{name: "ベビーカー"}, {name: "抱っこひも"}, {name: "チャイルドシート"}, {name: "その他"}])
baby_10.children.create([{name: "ミルク"}, {name: "ベビーフード"}, {name: "ベビー用食器"}, {name: "その他"}])
baby_11.children.create([{name: "ベッド"}, {name: "布団/毛布"}, {name: "イス"}, {name: "たんす"}, {name: "その他"}])
baby_12.children.create([{name: "お風呂のおもちゃ"}, {name: "がらがら"}, {name: "オルゴール"}, {name: "ベビージム"}, {name: "その他"}])
baby_13.children.create([{name: "お宮参り用品"}, {name: "お食い初め用品"}, {name: "アルバム"}, {name: "手形/足形"}, {name: "その他"}])
baby_14.children.create([{name: "母子手帳用品"}, {name: "その他"}])


# housing_1 = housing.children.create(name: "")
# housing_2 = housing.children.create(name: "")
# housing_3 = housing.children.create(name: "")
# housing_4 = housing.children.create(name: "")
# housing_5 = housing.children.create(name: "")
# housing_6 = housing.children.create(name: "")
# housing_7 = housing.children.create(name: "")
# housing_8 = housing.children.create(name: "")
# housing_9 = housing.children.create(name: "")
# housing_10 = housing.children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# housing_1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# housing_13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
            
# "本・音楽・ゲーム", "おもちゃ・ホビー・グッズ", "コスメ・香水・美容", "家電・スマホ・カメラ", "スポーツ・レジャー", "ハンドメイド", "チケット", "自転車・オートバイ", "その他"
# @category4 = Category.create(name:"インテリア・住まい・小物")
# category4s = [
#              {level2:"キッチン/食器",level2_children:["食器", "調理器具", "収納/キッチン雑貨", "弁当用品", "カトラリー(スプーン等)", "その他"]},
#              {level2:"ベッド/マットレス",level2_children:["シングルベッド", "ダブルベッド", "クイーンベッド", "キングベッド", "マットレス", "その他"]},
#              {level2:"ソファ/ソファベッド",level2_children:["ソファセット", "シングルソファ", "ラブソファ", "トリプルソファ", "オットマン", "その他"]},
#              {level2:"イス",level2_children:["一般", "スツール", "ダイニングチェア", "ハイバックチェア", "ロッキングチェア", "その他"]},
#              {level2:"テーブル",level2_children:["こたつ", "カウンターテーブル", "サイドテーブル", "センターテーブル", "ダイニングテーブル", "その他"]},
#              {level2:"収納家具",level2_children:["リビング収納", "キッチン収納", "玄関/屋外収納", "バス/トイレ収納", "本収納", "その他"]},
#              {level2:"ラグ/カーペット/マット",level2_children:["ラグ", "カーペット", "ホットカーペット", "玄関/キッチンマット", "トイレ/バスマット", "その他"]},
#              {level2:"カーテン/ブラインド",level2_children:["カーテン", "ブラインド", "ロールスクリーン", "のれん", "その他"]},
#              {level2:"ライト/証明",level2_children:["蛍光灯/電球", "天井照明", "フロアスタンド", "その他"]},
#              {level2:"寝具",level2_children:["布団/毛布", "枕", "シーツ/カバー", "その他"]},
#              {level2:"インテリア小物",level2_children:["ゴミ箱", "ウェルカムボード", "オルゴール", "クッション", "クッションカバー", "その他"]},
#              {level2:"季節/年中行事",level2_children:["正月", "成人式", "バレンタインデー", "ひな祭り", "子どもの日", "その他"]},
#              {level2:"その他"}
#             ]
# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
            
# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])

# _1 = .children.create(name: "")
# _2 = .children.create(name: "")
# _3 = .children.create(name: "")
# _4 = .children.create(name: "")
# _5 = .children.create(name: "")
# _6 = .children.create(name: "")
# _7 = .children.create(name: "")
# _8 = .children.create(name: "")
# _9 = .children.create(name: "")
# _10 = .children.create(name: "")
# _11 = .children.create(name: "")
# _12 = .children.create(name: "")
# _13 = .children.create(name: "")
# _14 = .children.create(name: "その他")

# _1.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _2.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _3.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _4.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _5.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _6.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _7.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _8.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _9.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _10.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _11.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _12.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _13.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _14.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _15.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
# _16.children.create([{name: ""}, {name: ""}, {name: ""}, {name: ""}, {name: "その他"}])
