# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

lady = Category.create(name:"レディース")
man = Category.create(name:"メンズ")
baby = Category.create(name:"ベビー・キッズ")
housing = Category.create(name:"インテリア・住まい・小物")
book = Category.create(name:"本・音楽・ゲーム")
toy = Category.create(name:"おもちゃ・ホビー・グッズ")
beauty = Category.create(name:"コスメ・香水・美容")
electronics = Category.create(name:"家電・スマホ・カメラ")
sports = Category.create(name:"スポーツ・レジャー")
handmade = Category.create(name:"ハンドメイド")
ticket = Category.create(name:"チケット")
car = Category.create(name:"自動車・オートバイ")
other = Category.create(name:"その他")


lady_1 = lady.children.create(name: "トップス")
lady_2 = lady.children.create(name: "ジャケット/アウター")
lady_3 = lady.children.create(name: "パンツ")
lady_4 = lady.children.create(name: "スカート")
lady_5 = lady.children.create(name: "ワンピース")
lady_6 = lady.children.create(name: "靴")
lady_7 = lady.children.create(name: "ルームウェア/パジャマ")
lady_8 = lady.children.create(name: "レッグウェア")
lady_9 = lady.children.create(name: "帽子")
lady_10 = lady.children.create(name: "バッグ")
lady_11 = lady.children.create(name: "アクセサリー")
lady_12 = lady.children.create(name: "ヘアアクセサリー")
lady_13 = lady.children.create(name: "小物")
lady_14 = lady.children.create(name: "時計")
lady_15 = lady.children.create(name: "ウィッグ/エクステ")
lady_16 = lady.children.create(name: "浴衣/水")
lady_17 = lady.children.create(name: "スーツ/フォーマル/ドレス")
lady_18 = lady.children.create(name: "マタニティ")
lady_19 = lady.children.create(name: "その他")

lady_1.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "キャミソール"}, {name: "タンクトップ"}, {name: "ホルターネック"}, {name: "ニット/セーター"}, {name: "チュニック"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "ベアトップ/チューブトップ"}, {name: "ジャージ"}, {name: "その他"}])
lady_2.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "レザージャケット"}, {name: "ダウンジャケット"}, {name: "ライダースジャケット"}, {name: "ミリタリージャケット"}, {name: "ダウンベスト"}, {name: "ジャンパー/ブルゾン"}, {name: "ポンチョ"}, {name: "ロングコート"}, {name: "トレンチコート"}, {name: "ダッフルコート"}, {name: "ピーコート"}, {name: "チェスターコート"}, {name: "モッズコート"}, {name: "スタジャン"}, {name: "毛皮/ファーコート"}, {name: "スプリングコート"}, {name: "スカジャン"}, {name: "その他"}])
lady_3.children.create([{name: "デニム/ジーンズ"}, {name: "ショートパンツ"}, {name: "カジュアルパンツ"}, {name: "ハーフパンツ"}, {name: "チノパン"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "クロップドパンツ"}, {name: "サロペット/オーバーオール"}, {name: "オールインワン"}, {name: "サルエルパンツ"}, {name: "ガウチョパンツ"}, {name: "その他"}])
lady_4.children.create([{name: "ミニスカート"}, {name: "ひざ丈スカート"}, {name: "ロングスカート"}, {name: "キュロット"}, {name: "その他"}])
lady_5.children.create([{name: "ミニワンピース"}, {name: "ひざ丈ワンピース"}, {name: "ロングワンピース"}, {name: "その他"}])
lady_6.children.create([{name: "ハイヒール/パンプス"}, {name: "ブーツ"}, {name: "サンダル"}, {name: "スニーカー"}, {name: "ミュール"}, {name: "モカシン"}, {name: "ローファー/革靴"}, {name: "フラットシューズ/バレエシューズ"}, {name: "長靴/レインシューズ"}, {name: "その他"}])
lady_7.children.create([{name: "パジャマ"}, {name: "ルームウェア"}, {name: "その他"}])
lady_8.children.create([{name: "ソックス"}, {name: "スパッツ/レギンス"}, {name: "ストッキング/タイツ"}, {name: "レッグウォーマー"}, {name: "その他"}])
lady_9.children.create([{name: "ニットキャップ/ビーニー"}, {name: "ハット"}, {name: "ハンチング/ベレー帽"}, {name: "キャップ"}, {name: "キャスケット"}, {name: "麦わら帽子"}, {name: "その他"}])
lady_10.children.create([{name: "ハンドバッグ"}, {name: "トートバッグ"}, {name: "エコバッグ"}, {name: "リュック/バックパック"}, {name: "ボストンバッグ"}, {name: "スポーツバッグ"}, {name: "ショルダーバッグ"}, {name: "クラッチバッグ"}, {name: "ポーチ/バニティ"}, {name: "ボディバッグ/ウェストバッグ"}, {name: "マザーズバッグ"}, {name: "メッセンジャーバッグ"}, {name: "ビジネスバッグ"}, {name: "旅行用バッグ/キャリーバッグ"}, {name: "ショップ袋"}, {name: "和装用バッグ"}, {name: "かごバッグ"}, {name: "その他"}])
lady_11.children.create([{name: "ネックレス"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "イヤリング"}, {name: "アンクレット"}, {name: "ブローチ/コサージュ"}, {name: "チャーム"}, {name: "その他"}])
lady_12.children.create([{name: "ヘアゴム/シュシュ"}, {name: "ヘアバンド/カチューシャ"}, {name: "ヘアピン"}, {name: "その他"}])
lady_13.children.create([{name: "長財布"}, {name: "折り財布"}, {name: "コインケース/小銭入れ"}, {name: "名刺入れ/定期入れ"}, {name: "キーケース"}, {name: "キーホルダー"}, {name: "手袋/アームカバー"}, {name: "ハンカチ"}, {name: "ベルト"}, {name: "マフラー/ショール"}, {name: "ストール/スヌード"}, {name: "バンダナ/スカーフ"}, {name: "ネックウォーマー"}, {name: "サスペンダー"}, {name: "サングラス/メガネ"}, {name: "モバイルケース/カバー"}, {name: "手帳"}, {name: "イヤマフラー"}, {name: "傘"}, {name: "レインコート/ポンチョ"}, {name: "ミラー"}, {name: "タバコグッズ"}, {name: "その他"}])
lady_14.children.create([{name: "腕時計(アナログ)"}, {name: "腕時計(デジタル)"}, {name: "ラバーベルト"}, {name: "レザーベルト"}, {name: "金属ベルト"},{name: "その他"}])
lady_15.children.create([{name: "前髪ウィッグ"}, {name: "ロングストレート"}, {name: "ロングカール"}, {name: "ショートストレート"}, {name: "ショートカール"}, {name: "その他"}])
lady_16.children.create([{name: "浴衣"}, {name: "着物"}, {name: "振袖"}, {name: "長襦袢/半襦袢"}, {name: "水着セパレート"}, {name: "水着ワンピース"}, {name: "水着スポーツ用"}, {name: "その他"}])
lady_17.children.create([{name: "スカートスーツ上下"}, {name: "パンツスーツ上下"}, {name: "ドレス"}, {name: "パーティバッグ"}, {name: "シューズ"}, {name: "ウェディング"}, {name: "その他"}])
lady_18.children.create([{name: "トップス"}, {name: "アウター"}, {name: "インナー"}, {name: "ワンピース"}, {name: "パンツ/スパッツ"}, {name: "スカート"}, {name: "パジャマ"}, {name: "授乳服"}, {name: "その他"}])
lady_19.children.create([{name: "コスプレ"}, {name: "下着"}, {name: "その他"}])


man_1 = man.children.create(name: "トップス")
man_2 = man.children.create(name: "ジャケット/アウター")
man_3 = man.children.create(name: "パンツ")
man_4 = man.children.create(name: "靴")
man_5 = man.children.create(name: "バッグ")
man_6 = man.children.create(name: "スーツ")
man_7 = man.children.create(name: "帽子")
man_8 = man.children.create(name: "アクセサリー")
man_9 = man.children.create(name: "小物")
man_10 = man.children.create(name: "時計")
man_11 = man.children.create(name: "水着")
man_12 = man.children.create(name: "レッグウェア")
man_13 = man.children.create(name: "アンダーウェア")
man_14 = man.children.create(name: "その他")

man_1.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ"}, {name: "ポロシャツ"}, {name: "タンクトップ"}, {name: "ニット/セーター"}, {name: "パーカー"}, {name: "カーディガン"}, {name: "スウェット"}, {name: "ジャージ"}, {name: "ベスト"}, {name: "その他"}])
man_2.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "レザージャケット"}, {name: "ダウンジャケット"}, {name: "ライダースジャケット"}, {name: "ミリタリージャケット"}, {name: "ナイロンジャケット"}, {name: "フライトジャケット"}, {name: "ダッフルコート"}, {name: "ピーコート"}, {name: "ステンカラーコート"}, {name: "トレンチコート"}, {name: "モッズコート"}, {name: "チェスターコート"}, {name: "スタジャン"}, {name: "スカジャン"}, {name: "ブルゾン"}, {name: "マウンテンパーカー"}, {name: "ダウンベスト"}, {name: "ポンチョ"}, {name: "カバーオール"}, {name: "その他"}])
man_3.children.create([{name: "デニム/ジーンズ"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "スラックス"}, {name: "チノパン"}, {name: "ショートパンツ"}, {name: "ペインターパンツ"}, {name: "サルエルパンツ"}, {name: "オーバーオール"}, {name: "その他"}])
man_4.children.create([{name: "スニーカー"}, {name: "サンダル"}, {name: "ブーツ"}, {name: "モカシン"}, {name: "ドレス/ビジネス"}, {name: "長靴/レインシューズ"}, {name: "デッキシューズ"}, {name: "その他"}])
man_5.children.create([{name: "ショルダーバッグ"}, {name: "トートバッグ"}, {name: "ボストンバッグ"}, {name: "リュック/バックパック"}, {name: "ウエストポーチ"}, {name: "ボディバッグ"}, {name: "ドラムバッグ"}, {name: "ビジネスバッグ"}, {name: "トラベルバッグ"}, {name: "メッセンジャーバッグ"}, {name: "エコバッグ"}, {name: "その他"}])
man_6.children.create([{name: "スーツジャケット"}, {name: "スーツベスト"}, {name: "スラックス"}, {name: "セットアップ"}, {name: "その他"}])
man_7.children.create([{name: "キャップ"}, {name: "ハット"}, {name: "ニットキャップ/ビーニー"}, {name: "ハンチング/ベレー帽"}, {name: "キャスケット"}, {name: "サンバイザー"}, {name: "その他"}])
man_8.children.create([{name: "ネックレス"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "アンクレット"}, {name: "その他"}])
man_9.children.create([{name: "長財布"}, {name: "折り財布"}, {name: "マネークリップ"}, {name: "コインケース/小銭入れ"}, {name: "名刺入れ/定期入れ"}, {name: "キーケース"}, {name: "キーホルダー"}, {name: "ネクタイ"}, {name: "手袋"}, {name: "ハンカチ"}, {name: "ベルト"}, {name: "マフラー"}, {name: "ストール"}, {name: "バンダナ"}, {name: "ネックウォーマー"}, {name: "サスペンダー"}, {name: "ウォレットチェーン"}, {name: "サングラス/メガネ"}, {name: "モバイルケース/カバー"}, {name: "手帳"}, {name: "ストラップ"}, {name: "ネクタイピン"}, {name: "カフリンクス"}, {name: "イヤマフラー"}, {name: "傘"}, {name: "レインコート"}, {name: "ミラー"}, {name: "タバコグッズ"}, {name: "その他"}])
man_10.children.create([{name: "腕時計(アナログ)"}, {name: "腕時計(デジタル)"}, {name: "ラバーベルト"}, {name: "レザーベルト"}, {name: "金属ベルト"}, {name: "その他"}])
man_11.children.create([{name: "一般水着"}, {name: "スポーツ用"}, {name: "アクセサリー"}, {name: "その他"}])
man_12.children.create([{name: "ソックス"}, {name: "スパッツ/レギンス"}, {name: "レッグウォーマー"}, {name: "その他"}])
man_13.children.create([{name: "トランクス"}, {name: "ボクサーパンツ"}, {name: "その他"}])
man_14.children.create([{name: "その他"}])


baby_1 = baby.children.create(name: "ベビー服(女の子用)~95cm")
baby_2 = baby.children.create(name: "ベビー服(男の子用)~95cm")
baby_3 = baby.children.create(name: "ベビー服(男女兼用)~95cm")
baby_4 = baby.children.create(name: "キッズ服(女の子用)100cm~")
baby_5 = baby.children.create(name: "キッズ服(男の子用)100cm~")
baby_6 = baby.children.create(name: "キッズ服(男女兼用)100cm~")
baby_7 = baby.children.create(name: "キッズ靴")
baby_8 = baby.children.create(name: "子ども用ファッション小物")
baby_9 = baby.children.create(name: "おむつ/トイレ/バス")
baby_10 = baby.children.create(name: "外出/移動用品")
baby_11 = baby.children.create(name: "授乳/食事")
baby_12 = baby.children.create(name: "ベビー家具/寝具/室内用品")
baby_13 = baby.children.create(name: "おもちゃ")
baby_14 = baby.children.create(name: "行事/記念品")
baby_15 = baby.children.create(name: "その他")

baby_1.children.create([{name: "トップス"}, {name: "アウター"}, {name: "パンツ"}, {name: "おくるみ"}, {name: "その他"}])
baby_2.children.create([{name: "トップス"}, {name: "アウター"}, {name: "パンツ"}, {name: "おくるみ"}, {name: "その他"}])
baby_3.children.create([{name: "トップス"}, {name: "アウター"}, {name: "パンツ"}, {name: "おくるみ"}, {name: "その他"}])
baby_4.children.create([{name: "コート"}, {name: "ジャケット"}, {name: "トップス"}, {name: "パンツ"}, {name: "その他"}])
baby_5.children.create([{name: "コート"}, {name: "ジャケット"}, {name: "トップス"}, {name: "パンツ"}, {name: "その他"}])
baby_6.children.create([{name: "コート"}, {name: "ジャケット"}, {name: "トップス"}, {name: "パンツ"}, {name: "その他"}])
baby_7.children.create([{name: "靴下"}, {name: "帽子"}, {name: "エプロン"}, {name: "サスペンダー"}, {name: "その他"}])
baby_8.children.create([{name: "おむつ用品"}, {name: "おまる"}, {name: "トレーニングパンツ"}, {name: "ベビーパス"}, {name: "その他"}])
baby_9.children.create([{name: "ベビーカー"}, {name: "抱っこひも"}, {name: "チャイルドシート"}, {name: "その他"}])
baby_10.children.create([{name: "ミルク"}, {name: "ベビーフード"}, {name: "ベビー用食器"}, {name: "その他"}])
baby_11.children.create([{name: "ベッド"}, {name: "布団/毛布"}, {name: "イス"}, {name: "たんす"}, {name: "その他"}])
baby_12.children.create([{name: "お風呂のおもちゃ"}, {name: "がらがら"}, {name: "オルゴール"}, {name: "ベビージム"}, {name: "その他"}])
baby_13.children.create([{name: "お宮参り用品"}, {name: "お食い初め用品"}, {name: "アルバム"}, {name: "手形/足形"}, {name: "その他"}])
baby_14.children.create([{name: "母子手帳用品"}, {name: "その他"}])


housing_1 = housing.children.create(name: "キッチン/食器")
housing_2 = housing.children.create(name: "ベッド/マットレス")
housing_3 = housing.children.create(name: "ソファ/ソファベッド")
housing_4 = housing.children.create(name: "イス")
housing_5 = housing.children.create(name: "テーブル")
housing_6 = housing.children.create(name: "収納家具")
housing_7 = housing.children.create(name: "ラグ/カーペット/マット")
housing_8 = housing.children.create(name: "カーテン/ブラインド")
housing_9 = housing.children.create(name: "ライト/証明")
housing_10 = housing.children.create(name: "寝具")
housing_11 = housing.children.create(name: "インテリア小物")
housing_12 = housing.children.create(name: "季節/年中行事")
housing_13 = housing.children.create(name: "その他")

housing_1.children.create([{name: "食器"}, {name: "調理器具"}, {name: "収納/キッチン雑貨"}, {name: "弁当用品"}, {name: "その他"}])
housing_2.children.create([{name: "シングルベッド"}, {name: "ダブルベッド"}, {name: "クイーンベッド"}, {name: "キングベッド"}, {name: "その他"}])
housing_3.children.create([{name: "ソファセット"}, {name: "シングルソファ"}, {name: "ラブソファ"}, {name: "トリプルソファ"}, {name: "その他"}])
housing_4.children.create([{name: "一般"}, {name: "スツール"}, {name: "ダイニングチェア"}, {name: "ハイバックチェア"}, {name: "その他"}])
housing_5.children.create([{name: "こたつ"}, {name: "カウンターテーブル"}, {name: "サイドテーブル"}, {name: "センターテーブル"}, {name: "その他"}])
housing_6.children.create([{name: "リビング収納"}, {name: "キッチン収納"}, {name: "玄関/屋外収納"}, {name: "バス/トイレ収納"}, {name: "その他"}])
housing_7.children.create([{name: "ラグ"}, {name: "カーペット"}, {name: "玄関/キッチンマット"}, {name: "トイレ/バスマット"}, {name: "その他"}])
housing_8.children.create([{name: "カーテン"}, {name: "ブラインド"}, {name: "ロールスクリーン"}, {name: "のれん"}, {name: "その他"}])
housing_9.children.create([{name: "蛍光灯/電球"}, {name: "天井照明"}, {name: "フロアスタンド"}, {name: "その他"}])
housing_10.children.create([{name: "布団/毛布"}, {name: "枕"}, {name: "シーツ/カバー"}, {name: "その他"}])
housing_11.children.create([{name: "ゴミ箱"}, {name: "ウェルカムボード"}, {name: "オルゴール"}, {name: "クッション"}, {name: "その他"}])
housing_12.children.create([{name: "正月"}, {name: "成人式"}, {name: "バレンタインデー"}, {name: "ひな祭り"}, {name: "その他"}])


book_1 = book.children.create(name: "本")
book_2 = book.children.create(name: "漫画")
book_3 = book.children.create(name: "雑誌")
book_4 = book.children.create(name: "CD")
book_5 = book.children.create(name: "DVD/ブルーレイ")
book_6 = book.children.create(name: "レコード")
book_7 = book.children.create(name: "テレビゲーム")
book_8 = book.children.create(name: "その他")

book_1.children.create([{name: "文学/小説"}, {name: "人文/社会"}, {name: "ノンフィクション/教養"}, {name: "洋書"}, {name: "その他"}])
book_2.children.create([{name: "全巻セット"}, {name: "少年漫画"}, {name: "少女漫画"}, {name: "青年漫画"}, {name: "女性漫画"}, {name: "その他"}])
book_3.children.create([{name: "アート/エンタメ/ホビー"}, {name: "ファッション"}, {name: "ニュース/総合"}, {name: "趣味/スポーツ"}, {name: "その他"}])
book_4.children.create([{name: "邦楽"}, {name: "洋楽"}, {name: "アニメ"}, {name: "クラシック"}, {name: "その他"}])
book_5.children.create([{name: "外国映画"}, {name: "日本映画"}, {name: "アニメ"}, {name: "TVドラマ"}, {name: "その他"}])
book_6.children.create([{name: "邦楽"}, {name: "洋楽"}, {name: "その他"}])
book_7.children.create([{name: "家庭用ゲーム本体"}, {name: "家庭用ゲームソフト"}, {name: "携帯用ゲーム本体"}, {name: "携帯用ゲームソフト"}, {name: "その他"}])
book_8.children.create([{name: "その他"}])


toy_1 = toy.children.create(name: "おもちゃ")
toy_2 = toy.children.create(name: "タレントグッズ")
toy_3 = toy.children.create(name: "コミック/アニメグッズ")
toy_4 = toy.children.create(name: "トレーディングカード")
toy_5 = toy.children.create(name: "フィギュア")
toy_6 = toy.children.create(name: "楽器/器材")
toy_7 = toy.children.create(name: "コレクション")
toy_8 = toy.children.create(name: "ミリタリー")
toy_9 = toy.children.create(name: "美術品")
toy_10 = toy.children.create(name: "アート用品")
toy_11 = toy.children.create(name: "その他")

toy_1.children.create([{name: "キャラクターグッズ"}, {name: "ぬいぐるみ"}, {name: "小物/アクセサリー"}, {name: "模型/プラモデル"}, {name: "その他"}])
toy_2.children.create([{name: "アイドル"}, {name: "ミュージシャン"}, {name: "タレント/お笑い芸人"}, {name: "スポーツ選手"}, {name: "その他"}])
toy_3.children.create([{name: "ストラップ"}, {name: "キーホルダー"}, {name: "バッジ"}, {name: "カード"}, {name: "その他"}])
toy_4.children.create([{name: "遊戯王"}, {name: "マジック・ザ・ギャザリング"}, {name: "ポケモンカードゲーム"}, {name: "デュエルマスターズ"}, {name: "その他"}])
toy_5.children.create([{name: "コミック/アニメ"}, {name: "特撮"}, {name: "ゲームキャラクター"}, {name: "SF/ファンタジー/ホラー"}, {name: "その他"}])
toy_6.children.create([{name: "エレキギター"}, {name: "アコースティックギター"}, {name: "ベース"}, {name: "エフェクター"}, {name: "その他"}])
toy_7.children.create([{name: "武具"}, {name: "使用済切手/官製はがき"}, {name: "旧貨幣/金貨/銀貨/記念硬貨"}, {name: "印刷物"}, {name: "その他"}])
toy_8.children.create([{name: "トイガン"}, {name: "個人装備"}, {name: "その他"}])
toy_9.children.create([{name: "陶芸"}, {name: "ガラス"}, {name: "漆芸"}, {name: "金属工芸"}, {name: "その他"}])
toy_10.children.create([{name: "画材"}, {name: "額縁"}, {name: "その他"}])
toy_11.children.create([{name: "トランプ/UNO"}, {name: "カルタ/百人一首"}, {name: "ダーツ"}, {name: "ビリヤード"}, {name: "その他"}])


beauty_1 = beauty.children.create(name: "ベースメイク")
beauty_2 = beauty.children.create(name: "メイクアップ")
beauty_3 = beauty.children.create(name: "ネイルケア")
beauty_4 = beauty.children.create(name: "香水")
beauty_5 = beauty.children.create(name: "スキンケア/基礎化粧品")
beauty_6 = beauty.children.create(name: "ヘアケア")
beauty_7 = beauty.children.create(name: "ボディケア")
beauty_8 = beauty.children.create(name: "オーラルケア")
beauty_9 = beauty.children.create(name: "リラクゼーション")
beauty_10 = beauty.children.create(name: "ダイエット")
beauty_11 = beauty.children.create(name: "その他")

beauty_1.children.create([{name: "ファンデーション"}, {name: "化粧下地"}, {name: "コントロールカラー"}, {name: "BBクリーム"}, {name: "その他"}])
beauty_2.children.create([{name: "アイシャドウ"}, {name: "口紅"}, {name: "リップグロス"}, {name: "チーク"}, {name: "その他"}])
beauty_3.children.create([{name: "ネイルカラー"}, {name: "カラージェル"}, {name: "ネイルベースコート/トップコート"}, {name: "ネイルアート用品"}, {name: "その他"}])
beauty_4.children.create([{name: "香水(女性用)"}, {name: "香水(男性用)"}, {name: "ユニセックス"}, {name: "ボディミスト"}, {name: "その他"}])
beauty_5.children.create([{name: "化粧水/ローション"}, {name: "乳液/ミルク"}, {name: "美容液"}, {name: "フェイスクリーム"}, {name: "その他"}])
beauty_6.children.create([{name: "シャンプー"}, {name: "トリートメント"}, {name: "コンディショナー"}, {name: "リンス"}, {name: "その他"}])
beauty_7.children.create([{name: "オイル/クリーム"}, {name: "ハンドクリーム"}, {name: "ローション"}, {name: "日焼け止め/サンオイル"}, {name: "その他"}])
beauty_8.children.create([{name: "口臭防止/エチケット用品"}, {name: "歯ブラシ"}, {name: "その他"}])
beauty_9.children.create([{name: "エッセンシャルオイル"}, {name: "芳香器"}, {name: "お香/香炉"}, {name: "キャンドル"}, {name: "その他"}])
beauty_10.children.create([{name: "ダイエット食品"}, {name: "エクササイズ用品"}, {name: "体重計"}, {name: "体脂肪計"}, {name: "その他"}])
beauty_11.children.create([{name: "健康用品"}, {name: "看護/介護用品"}, {name: "救急/衛生用品"}, {name: "その他"}])


electronics_1 = electronics.children.create(name: "スマートフォン/携帯電話")
electronics_2 = electronics.children.create(name: "スマホアクセサリー")
electronics_3 = electronics.children.create(name: "PC/タブレット")
electronics_4 = electronics.children.create(name: "カメラ")
electronics_5 = electronics.children.create(name: "テレビ/映像機器")
electronics_6 = electronics.children.create(name: "オーディオ機器")
electronics_7 = electronics.children.create(name: "美容/健康")
electronics_8 = electronics.children.create(name: "冷暖房/空調")
electronics_9 = electronics.children.create(name: "生活家電")
electronics_10 = electronics.children.create(name: "その他")

electronics_1.children.create([{name: "スマートフォン本体"}, {name: "バッテリー/充電器"}, {name: "携帯電話本体"}, {name: "PHS本体"}, {name: "その他"}])
electronics_2.children.create([{name: "Android用ケース"}, {name: "iPhone用ケース"}, {name: "カバー"}, {name: "イヤホンジャック"}, {name: "その他"}])
electronics_3.children.create([{name: "タブレット"}, {name: "ノートPC"}, {name: "デスクトップ型PC"}, {name: "ディスプレイ"}, {name: "その他"}])
electronics_4.children.create([{name: "デジタルカメラ"}, {name: "ビデオカメラ"}, {name: "レンズ"}, {name: "フィルムカメラ"}, {name: "その他"}])
electronics_5.children.create([{name: "テレビ"}, {name: "プロジェクター"}, {name: "ブルーレイレコーダー"}, {name: "DVDレコーダー"}, {name: "その他"}])
electronics_6.children.create([{name: "ポータブルプレーヤー"}, {name: "イヤフォン"}, {name: "ヘッドフォン"}, {name: "アンプ"}, {name: "その他"}])
electronics_7.children.create([{name: "ヘアドライヤー"}, {name: "ヘアアイロン"}, {name: "美容機器"}, {name: "電気シェーバー"}, {name: "その他"}])
electronics_8.children.create([{name: "エアコン"}, {name: "空気清浄機"}, {name: "加湿器"}, {name: "扇風機"}, {name: "その他"}])
electronics_9.children.create([{name: "冷蔵庫"}, {name: "洗濯機"}, {name: "炊飯器"}, {name: "電子レーズン/オーブン"}, {name: "その他"}])
electronics_10.children.create([{name: "その他"}])


sports_1 = sports.children.create(name: "ゴルフ")
sports_2 = sports.children.create(name: "フィッシング")
sports_3 = sports.children.create(name: "自転車")
sports_4 = sports.children.create(name: "トレーニング/エクササイズ")
sports_5 = sports.children.create(name: "野球")
sports_6 = sports.children.create(name: "サッカー/フットサル")
sports_7 = sports.children.create(name: "テニス")
sports_8 = sports.children.create(name: "スノーボード")
sports_9 = sports.children.create(name: "スキー")
sports_10 = sports.children.create(name: "その他スポーツ")
sports_11 = sports.children.create(name: "アウトドア")
sports_12 = sports.children.create(name: "その他")

sports_1.children.create([{name: "クラブ"}, {name: "ウェア(男性用)"}, {name: "ウェア(女性用)"}, {name: "バッグ"}, {name: "その他"}])
sports_2.children.create([{name: "ロッド"}, {name: "リール"}, {name: "ルアー用品"}, {name: "ウェア"}, {name: "その他"}])
sports_3.children.create([{name: "自転車本体"}, {name: "ウェア"}, {name: "パーツ"}, {name: "アクセサリー"}, {name: "その他"}])
sports_4.children.create([{name: "ランニング"}, {name: "ウォーキング"}, {name: "ヨガ"}, {name: "トレーニング用品"}, {name: "その他"}])
sports_5.children.create([{name: "ウェア"}, {name: "シューズ"}, {name: "グローブ"}, {name: "バット"}, {name: "その他"}])
sports_6.children.create([{name: "ウェア"}, {name: "シューズ"}, {name: "ボール"}, {name: "アクセサリー"}, {name: "その他"}])
sports_7.children.create([{name: "ラケット(硬式用)"}, {name: "ラケット(軟式用)"}, {name: "ウェア"}, {name: "シューズ"}, {name: "その他"}])
sports_8.children.create([{name: "ボード"}, {name: "バインディング"}, {name: "ブーツ(男性用)"}, {name: "ブーツ(女性用)"}, {name: "その他"}])
sports_9.children.create([{name: "板"}, {name: "ブーツ(男性用)"}, {name: "ブーツ(女性用)"}, {name: "ビンディング"}, {name: "その他"}])
sports_10.children.create([{name: "ダンス/バレエ"}, {name: "サーフィン"}, {name: "バスケットボール"}, {name: "バドミントン"}, {name: "その他"}])
sports_11.children.create([{name: "テント/タープ"}, {name: "ライト/ランタン"}, {name: "寝袋/寝具"}, {name: "テーブル/チェア"}, {name: "その他"}])
sports_12.children.create([{name: "旅行用品"}, {name: "その他"}])


handmade_1 = handmade.children.create(name: "アクセサリー(女性用)")
handmade_2 = handmade.children.create(name: "ファッション/小物")
handmade_3 = handmade.children.create(name: "アクセサリー/時計")
handmade_4 = handmade.children.create(name: "日用品/インテリア")
handmade_5 = handmade.children.create(name: "趣味/おもちゃ")
handmade_6 = handmade.children.create(name: "キッズ/ベビー")
handmade_7 = handmade.children.create(name: "素材/材料")
handmade_8 = handmade.children.create(name: "二次創作物")
handmade_9 = handmade.children.create(name: "その他")

handmade_1.children.create([{name: "ピアス"}, {name: "イヤリング"}, {name: "ネックレス"}, {name: "ブレスレット"}, {name: "その他"}])
handmade_2.children.create([{name: "バッグ(女性用)"}, {name: "バッグ(男性用)"}, {name: "財布(女性用)"}, {name: "財布(男性用)"}, {name: "その他"}])
handmade_3.children.create([{name: "アクセサリー(男性用)"}, {name: "時計(女性用)"}, {name: "時計(男性用)"}, {name: "その他"}])
handmade_4.children.create([{name: "キッチン用品"}, {name: "家具"}, {name: "文房具"}, {name: "アート/写真"}, {name: "その他"}])
handmade_5.children.create([{name: "クラフト/布製品"}, {name: "おもちゃ/人形"}, {name: "その他"}])
handmade_6.children.create([{name: "ファッション雑貨"}, {name: "スタイ/よだれかけ"}, {name: "外出用件"}, {name: "ネームタグ"}, {name: "その他"}])
handmade_7.children.create([{name: "各種パーツ"}, {name: "生地/糸"}, {name: "型紙/パターン"}, {name: "その他"}])


ticket_1 = ticket.children.create(name: "音楽")
ticket_2 = ticket.children.create(name: "スポーツ")
ticket_3 = ticket.children.create(name: "演劇/芸能")
ticket_4 = ticket.children.create(name: "イベント")
ticket_5 = ticket.children.create(name: "映画")
ticket_6 = ticket.children.create(name: "施設利用券")
ticket_7 = ticket.children.create(name: "優待券/割引券")
ticket_8 = ticket.children.create(name: "その他")

ticket_1.children.create([{name: "男性アイドル"}, {name: "女性アイドル"}, {name: "韓流"}, {name: "国内アーティスト"}, {name: "その他"}])
ticket_2.children.create([{name: "サッカー"}, {name: "野球"}, {name: "テニス"}, {name: "格闘技/プロレス"}, {name: "その他"}])
ticket_3.children.create([{name: "ミュージカル"}, {name: "演劇"}, {name: "伝統芸能"}, {name: "落語"}, {name: "その他"}])
ticket_4.children.create([{name: "声優/アニメ"}, {name: "キッズ/ファミリー"}, {name: "トークショー/講演会"}, {name: "その他"}])
ticket_5.children.create([{name: "邦画"}, {name: "洋画"}, {name: "その他"}])
ticket_6.children.create([{name: "遊園地/テーマパーク"}, {name: "美術館/博物館"}, {name: "スキー場"}, {name: "ゴルフ場"}, {name: "その他"}])
ticket_7.children.create([{name: "ショッピング"}, {name: "レストラン/食事券"}, {name: "フード/ドリンク券"}, {name: "宿泊券"}, {name: "その他"}])


car_1 = car.children.create(name: "自動車本体")
car_2 = car.children.create(name: "自動車タイヤ/ホイール")
car_3 = car.children.create(name: "自動車パーツ")
car_4 = car.children.create(name: "自動車アクセサリー")
car_5 = car.children.create(name: "オートバイ車体")
car_6 = car.children.create(name: "オートバイパーツ")
car_7 = car.children.create(name: "オートバイアクセサリー")
car_8 = car.children.create(name: "その他")

car_1.children.create([{name: "国内自動車本体"}, {name: "外国自動車本体"}, {name: "その他"}])
car_2.children.create([{name: "タイヤ/ホイールセット"}, {name: "タイヤ"}, {name: "ホイール"}, {name: "その他"}])
car_3.children.create([{name: "サスペンション"}, {name: "ブレーキ"}, {name: "外装/エアロパーツ"}, {name: "ライト"}, {name: "その他"}])
car_4.children.create([{name: "車体アクセサリー"}, {name: "カーナビ"}, {name: "カーオーディオ"}, {name: "車外アクセサリー"}, {name: "その他"}])
car_6.children.create([{name: "タイヤ"}, {name: "マフラー"}, {name: "エンジン/冷却装置"}, {name: "カウル/フェンダー/外装"}, {name: "その他"}])
car_7.children.create([{name: "ヘルメット/シールド"}, {name: "バイクウェア/装備"}, {name: "アクセサリー"}, {name: "メンテナンス"}, {name: "その他"}])


other_1 = other.children.create(name: "まとめ売り")
other_2 = other.children.create(name: "ペット用品")
other_3 = other.children.create(name: "食品")
other_4 = other.children.create(name: "飲料/酒")
other_5 = other.children.create(name: "日用品/生活雑貨/旅行")
other_6 = other.children.create(name: "アンティーク/コレクション")
other_7 = other.children.create(name: "文房具/事務用品")
other_8 = other.children.create(name: "事務/店舗用品")
other_9 = other.children.create(name: "その他")

other_2.children.create([{name: "ペットフード"}, {name: "犬用品"}, {name: "猫用品"}, {name: "魚用品/水草"}, {name: "その他"}])
other_3.children.create([{name: "菓子"}, {name: "米"}, {name: "野菜"}, {name: "果物"}, {name: "その他"}])
other_4.children.create([{name: "コーヒー"}, {name: "ソフトドリンク"}, {name: "ミネラルウォーター"}, {name: "茶"}, {name: "その他"}])
other_5.children.create([{name: "タオル/バス"}, {name: "日用品/生活雑貨"}, {name: "洗剤/柔軟剤"}, {name: "旅行用品"}, {name: "その他"}])
other_6.children.create([{name: "雑貨"}, {name: "工芸品"}, {name: "家具"}, {name: "印刷物"}, {name: "その他"}])
other_7.children.create([{name: "筆記具"}, {name: "ノート/メモ帳"}, {name: "テープ/マスキングテープ"}, {name: "カレンダー/スケジュール"}, {name: "その他"}])
other_8.children.create([{name: "オフィス用品一般"}, {name: "オフィス家具"}, {name: "店舗用品"}, {name: "OA機器"}, {name: "その他"}])